[2023-06-29 08:23:00,095] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-29 08:23:00,138] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-29 08:23:00,139] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:23:00,139] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-06-29 08:23:00,139] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:23:00,165] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-05-01 00:00:00+00:00
[2023-06-29 08:23:00,174] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2023-06-29 08:23:00,181] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'apartment_transaction_etl_dag', 'run_etl_task', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/apartment_transaction_dag.py', '--cfg-path', '/tmp/tmp161urhyv', '--error-file', '/tmp/tmpqplq55wr']
[2023-06-29 08:23:00,182] {standard_task_runner.py:77} INFO - Job 24: Subtask run_etl_task
[2023-06-29 08:23:00,305] {logging_mixin.py:109} INFO - Running <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [running]> on host d3599d0cd7b8
[2023-06-29 08:23:00,460] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=apartment_transaction_etl_dag
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T00:00:00+00:00
[2023-06-29 08:23:00,467] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-06-29 08:23:00.467834+00:00
[2023-06-29 08:23:00,468] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-06-29 08:23:00.468140+00:00
[2023-06-29 08:23:00,468] {logging_mixin.py:109} INFO - Connecting to DB
[2023-06-29 08:23:00,493] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-06-29 08:23:00.468140+00:00
[2023-06-29 08:23:00,494] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-06-29 08:23:00.494078+00:00
[2023-06-29 08:23:00,494] {logging_mixin.py:109} INFO - Reading dataset from https://gist.githubusercontent.com/mmphego/5b6fc4d6dc3c8fba4fce9d994a2fe16b/raw/ab5df0e76812e13df5b31e466a5fb787fac0599a/wine_quality.csv
[2023-06-29 08:23:01,584] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 165, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 116, in extract
    payload = "LAWD_CD=" + code + "&" + "DEAL_YMD=" + date + "&" + "serviceKey=" + CONFIG["SERVICE_KEY"] + "&"
NameError: name 'date' is not defined
[2023-06-29 08:23:01,685] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=apartment_transaction_etl_dag, task_id=run_etl_task, execution_date=20230501T000000, start_date=20230629T082300, end_date=20230629T082301
[2023-06-29 08:23:01,732] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task run_etl_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 165, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 116, in extract
    payload = "LAWD_CD=" + code + "&" + "DEAL_YMD=" + date + "&" + "serviceKey=" + CONFIG["SERVICE_KEY"] + "&"
NameError: name 'date' is not defined
[2023-06-29 08:23:01,793] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-29 08:23:02,049] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-29 09:01:25,725] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-29 09:01:25,808] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-29 09:01:25,809] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 09:01:25,809] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-06-29 09:01:25,809] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 09:01:25,948] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-05-01 00:00:00+00:00
[2023-06-29 09:01:25,963] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2023-06-29 09:01:25,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'apartment_transaction_etl_dag', 'run_etl_task', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/apartment_transaction_dag.py', '--cfg-path', '/tmp/tmp9ol54itv', '--error-file', '/tmp/tmphb_jxj5n']
[2023-06-29 09:01:25,975] {standard_task_runner.py:77} INFO - Job 70: Subtask run_etl_task
[2023-06-29 09:01:26,241] {logging_mixin.py:109} INFO - Running <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-05-01T00:00:00+00:00 [running]> on host d3599d0cd7b8
[2023-06-29 09:01:26,480] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=apartment_transaction_etl_dag
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T00:00:00+00:00
[2023-06-29 09:01:26,481] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-06-29 09:01:26.481830+00:00
[2023-06-29 09:01:26,482] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-06-29 09:01:26.482032+00:00
[2023-06-29 09:01:26,482] {logging_mixin.py:109} INFO - Connecting to DB
[2023-06-29 09:01:26,660] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-06-29 09:01:26.482032+00:00
[2023-06-29 09:01:26,660] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-06-29 09:01:26.660811+00:00
[2023-06-29 09:01:27,927] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-06-29 09:01:27,996] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 92. PIDs of all processes in the group: [92]
[2023-06-29 09:01:27,996] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 92
[2023-06-29 09:01:27,998] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-29 09:01:33,902] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-06-29 09:01:33,904] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 92. PIDs of all processes in the group: [92]
[2023-06-29 09:01:33,904] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 92
